- depictsId: Q870
  name: Train
  limit: 250
  category: Category:Trains
  exclude:
  - Category:Steam locomotives
  - Category:Rail transport modelling
  excludeRegex: "/(Videos|art|Models|Station|Maintenance Center)/i"

- depictsId: Q171043
  name: Steam locomotive / train
  limit: 250
  category: Category:Steam locomotives
  exclude:
  - Category:Curiosities of Locomotive Design
  - Category:Disassembled steam locomotives
  - Category:Electric-steam locomotives
  - Category:Steam locomotive events
  - Category:Steam locomotive parts
  - Category:Steam locomotive surfing
  - Category:Steam heated trains
  - Category:Steam locomotive boiler blowdown
  - Category:Steam locomotive driving cabs
  - Category:Steam locomotive interiors
  - Category:Rail transport modelling
  excludeRegex: "/(Videos|art|Model|Station|Maintenance Center)/i"
