/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Callback: typeof import('./components/Callback.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    RecentChanges: typeof import('./components/RecentChanges.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Wikidata: typeof import('./components/Wikidata.vue')['default']
  }
}
