name: Composer lint

on:
  pull_request:
  push:

jobs:
  composer-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: shivammathur/setup-php@v2
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          php-version: 8.2
          coverage: none
      - uses: "ramsey/composer-install@v1"
      - run: composer lint
